services:
  - type: web
    name:  FastAPI
    env: docker
    plan: free
    repo: https://github.com/tabahra2015/FastAPI
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: 8000
